export type RootStackParamList = {
  Splash: undefined;
  WelcomeOnboarding: undefined;
  RoleSelection: undefined;
  Login: undefined;
  SignUp: undefined;
  Verification: undefined;
  ForgotPassword: undefined;
  Onboarding: undefined;
  CompanyInformation: undefined;
  CompanyDetails: undefined;
  RecruitmentPreferences: undefined;
  CompanyProfileCompletion: undefined;
  CompanyReviewComplete: undefined;
  CompanyTabs: undefined;
  AcademicInfo: undefined;
  Skills: undefined;
  CareerInterests: undefined;
  PreferredLocation: undefined;
  ProfileCompletion: undefined;
  HomeDashboard: undefined;
  StudentTabs: undefined;
  UniversityInfo: undefined;
  InstitutionDetails: undefined;
  CareerServicesSetup: undefined;
  ReviewComplete: undefined;
  UniversityDashboard: undefined;
  PlacementAnalytics: undefined;
  PlacementOverview: undefined;
  StudentMonitoring: undefined;
  CompanyEngagement: undefined;
  Reports: undefined;
  Settings: undefined;
  InternshipDetails: undefined;

  // Student application flow
  ApplicationReview: { internship: any } | undefined;
  ResumeSelection: { internship: any; resumeId?: string } | undefined;
  AdditionalInfo: { internship: any; resumeId?: string } | undefined;
  PortfolioLinks: { internship: any; resumeId?: string; coverLetter?: string; motivation?: string; whyThis?: string; strongCandidate?: string } | undefined;
  Availability: { internship: any; resumeId?: string; coverLetter?: string; motivation?: string; whyThis?: string; strongCandidate?: string; portfolioLinks?: any } | undefined;
  ReviewApplication: { internship: any; resumeId?: string; coverLetter?: string; motivation?: string; whyThis?: string; strongCandidate?: string; portfolioLinks?: any; availability?: any } | undefined;
  ApplicationSubmitted: { applicationId?: string; company?: string; title?: string } | undefined;
  MyApplications: undefined;
  ApplicationDetails: { applicationId: string } | undefined;
  Notifications: undefined;
  StudentChatScreen: { conversationId: string; participantName: string; participantInitials: string; participantColor: string; internshipTitle?: string } | undefined;

  // Employer screens
  ApplicantProfile: { applicationId: string } | undefined;
  InterviewSchedule: { applicationId: string } | undefined;
  OfferSend: { applicationId: string } | undefined;
  PostInternshipWizard: undefined;
  Messages: undefined;
  ChatScreen: { conversationId: string; participantName: string; participantInitials: string; participantColor: string; internshipTitle?: string } | undefined;
  Insights: undefined;
  PremiumPaywall: undefined;
  Payment: undefined;
  PremiumConfirmation: undefined;
  PremiumManage: undefined;
};
