/**
 * SettingsScreen.tsx
 * ─────────────────────────────────────────────────────────────────
 * InternLink — Settings (Settings tab for university users)
 *
 * Content (from design):
 *  - Header: back arrow + "Settings" title
 *  - Profile card: avatar, name, email, chevron (tap to edit profile)
 *  - "ACCOUNT" section: Personal info, Email & password, Connected accounts
 *  - "PREFERENCES" section: Notifications, Privacy, Language, Appearance
 *  - "SUPPORT" section: Help center, Send feedback
 *  - "Sign out" text link at the very bottom (red, no background)
 *  - Bottom tab bar with "Settings" highlighted as active
 *
 * HOW TO USE:
 *  1. Drop inside your screens/ or app/ folder
 *  2. Add to App.tsx:
 *     import SettingsScreen from './app/SettingsScreen';
 *     <Stack.Screen name="Settings" component={SettingsScreen} />
 * ─────────────────────────────────────────────────────────────────
 */

// ─── IMPORTS ─────────────────────────────────────────────────────
import React, { useState } from 'react';
import {
  View,
  Text,
  TouchableOpacity,
  StyleSheet,
  StatusBar,
  ScrollView,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context'; // non-deprecated version
import { Ionicons } from '@expo/vector-icons';


// ─── COLOR PALETTE ───────────────────────────────────────────────
const COLORS = {
  background:        '#F5FBFA', // mint — full screen background
  backBtnBg:         '#FFFFFF', // back arrow circle background
  backArrow:         '#0D3B47',
  headerTitle:       '#0D3B47', // "Settings"

  // Profile card
  profileCardBg:     '#FFFFFF',
  avatarBg:          '#0D3B47', // dark teal circle with initials
  avatarText:        '#FFFFFF',
  profileName:       '#0D3B47',
  profileEmail:      '#9BB8B4',
  chevron:           '#C7DAD7',

  // Section labels (ACCOUNT, PREFERENCES, SUPPORT)
  sectionLabel:      '#4A7C75',

  // Setting rows
  rowBg:             '#FFFFFF',
  rowText:           '#0D3B47',

  // Sign out link
  signOutText:       '#E0524C', // red

  // Bottom tab bar
  tabBarBg:          '#FFFFFF',
  tabActive:         '#2EC4B6',
  tabInactive:       '#9BB8B4',
};


// ─── DATA ─────────────────────────────────────────────────────────

// Each settings section has a label and a list of rows.
// Storing everything in this nested array structure means the entire
// page (every section, every row) is generated by looping twice —
// once over SETTINGS_SECTIONS, then once over each section's `items`.
// Adding a whole new section, or one more row to an existing section,
// is just an edit to this data — no new JSX needs to be written.
const SETTINGS_SECTIONS = [
  {
    id: 'account',
    label: 'ACCOUNT',
    items: [
      { id: 'personalInfo', title: 'Personal info' },
      { id: 'emailPassword', title: 'Email & password' },
      { id: 'connectedAccounts', title: 'Connected accounts' },
    ],
  },
  {
    id: 'preferences',
    label: 'PREFERENCES',
    items: [
      { id: 'notifications', title: 'Notifications' },
      { id: 'privacy', title: 'Privacy' },
      { id: 'language', title: 'Language' },
      { id: 'appearance', title: 'Appearance' },
    ],
  },
  {
    id: 'support',
    label: 'SUPPORT',
    items: [
      { id: 'helpCenter', title: 'Help center' },
      { id: 'sendFeedback', title: 'Send feedback' },
    ],
  },
];

// Bottom tab bar items — same set used across all university screens.
// "settings" stays highlighted since this screen IS that tab.



// ─── MAIN SCREEN COMPONENT ───────────────────────────────────────
export default function SettingsScreen({ navigation }: any) {

  // This screen lives on the "Settings" tab, so it starts active
  const [setActiveTab] = useState('settings');

  // Placeholder profile data — later this would come from your
  // logged-in user's data (auth context, backend, etc.)
  const profile = {
    initials: 'KB',
    name: 'Kenneth Baidoo',
    email: 'kenneth.baidoo@uni.edu',
  };

  // Called when the back arrow is tapped
  const handleBackPress = () => {
    console.log('Back tapped');
    navigation.goBack();
  };

  // Called when the profile card itself is tapped
  const handleProfilePress = () => {
    console.log('Opening profile editor');
    navigation.navigate('EditProfile');
  };

  // Called when any individual settings row is tapped.
  // Using one shared handler (instead of one function per row) keeps
  // this simple — the rowId tells us which row was pressed.
  const handleRowPress = (rowId: string) => {
    console.log('Opening setting:', rowId);
    // TODO: navigate to the matching screen for this setting, e.g.:
    // if (rowId === 'notifications') navigation.navigate('NotificationSettings');
  };

  // Called when "Sign out" is tapped
  const handleSignOut = () => {
    console.log('Signing out...');
    // TODO: clear auth tokens/session, then:
    navigation.reset({ index: 0, routes: [{ name: 'Login' }] });
  };


  return (
    <SafeAreaView style={styles.safeArea}>
      <StatusBar barStyle="dark-content" backgroundColor={COLORS.background} />

      {/* Main scrollable content sits above the fixed bottom tab bar */}
      <ScrollView
        contentContainerStyle={styles.scrollContent}
        showsVerticalScrollIndicator={false}
      >

        {/* ── HEADER ROW: back arrow + title ──────────────────────── */}
        <View style={styles.header}>
          <TouchableOpacity
            style={styles.backBtn}
            onPress={handleBackPress}
            activeOpacity={0.7}
          >
            <Ionicons
              name="arrow-back-outline"
              size={22}
              color={COLORS.backArrow}
            />
          </TouchableOpacity>

          <Text style={styles.headerTitle}>Settings</Text>
        </View>
        {/* ── END HEADER ──────────────────────────────────────────── */}


        {/* ── PROFILE CARD ─────────────────────────────────────────── */}
        <TouchableOpacity
          style={styles.profileCard}
          onPress={handleProfilePress}
          activeOpacity={0.85}
        >
          {/* Left: avatar circle with initials */}
          <View style={styles.avatar}>
            <Text style={styles.avatarText}>{profile.initials}</Text>
          </View>

          {/* Middle: name + email, fills remaining space */}
          <View style={styles.profileTextBlock}>
            <Text style={styles.profileName}>{profile.name}</Text>
            <Text style={styles.profileEmail}>{profile.email}</Text>
          </View>

          {/* Right: chevron indicating this row is tappable */}
          <Ionicons
            name="chevron-forward-outline"
            size={18}
            color={COLORS.chevron}
          />
        </TouchableOpacity>
        {/* ── END PROFILE CARD ────────────────────────────────────── */}


        {/* ── SETTINGS SECTIONS ────────────────────────────────────── */}
        {/*
          Outer .map() loops over each section (ACCOUNT, PREFERENCES,
          SUPPORT). Inner .map() loops over that section's individual
          rows. This two-level loop is what generates the whole page
          from the SETTINGS_SECTIONS data above.
        */}
        {SETTINGS_SECTIONS.map((section) => (
          <View key={section.id} style={styles.section}>

            {/* Section label, e.g. "ACCOUNT" */}
            <Text style={styles.sectionLabel}>{section.label}</Text>

            {/* Rounded card containing all rows for this section */}
            <View style={styles.sectionCard}>
              {section.items.map((item, index) => (
                <TouchableOpacity
                  key={item.id}
                  style={[
                    styles.settingRow,
                    // No bottom border on the very last row in each section
                    index === section.items.length - 1 && styles.settingRowLast,
                  ]}
                  onPress={() => handleRowPress(item.id)}
                  activeOpacity={0.7}
                >
                  <Text style={styles.rowText}>{item.title}</Text>
                  <Ionicons
                    name="chevron-forward-outline"
                    size={18}
                    color={COLORS.chevron}
                  />
                </TouchableOpacity>
              ))}
            </View>

          </View>
        ))}
        {/* ── END SETTINGS SECTIONS ───────────────────────────────── */}


        {/* ── SIGN OUT LINK ─────────────────────────────────────────── */}
        <TouchableOpacity
          style={styles.signOutBtn}
          onPress={handleSignOut}
          activeOpacity={0.7}
        >
          <Text style={styles.signOutText}>Sign out</Text>
        </TouchableOpacity>
        {/* ── END SIGN OUT LINK ───────────────────────────────────── */}

      </ScrollView>


      {/* ── BOTTOM TAB BAR ─────────────────────────────────────────
          Sits outside the ScrollView so it stays fixed at the bottom
          while the content above scrolls underneath it.
      */}

    </SafeAreaView>
  );
}


// ─── STYLES ──────────────────────────────────────────────────────
const styles = StyleSheet.create({

  safeArea: {
    flex: 1,
    backgroundColor: COLORS.background,
  },

  // Scrollable content — leaves room at the bottom so the tab bar
  // doesn't cover the last items
  scrollContent: {
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 100, // extra space so content isn't hidden behind tab bar
  },

  // ── Header ────────────────────────────────────────────────────
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 16,
  },
  backBtn: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: COLORS.backBtnBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: COLORS.headerTitle,
  },

  // ── Profile card ──────────────────────────────────────────────
  profileCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.profileCardBg,
    borderRadius: 16,
    padding: 14,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 3,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: COLORS.avatarBg,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 14,
  },
  avatarText: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.avatarText,
  },
  profileTextBlock: {
    flex: 1, // fills space between avatar and chevron
  },
  profileName: {
    fontSize: 15,
    fontWeight: '700',
    color: COLORS.profileName,
    marginBottom: 2,
  },
  profileEmail: {
    fontSize: 12,
    color: COLORS.profileEmail,
  },

  // ── Section label + card ──────────────────────────────────────
  section: {
    marginBottom: 20,
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: '700',
    color: COLORS.sectionLabel,
    letterSpacing: 1,
    marginBottom: 8,
    marginLeft: 4,
  },
  // The rounded white card that wraps all rows in one section
  sectionCard: {
    backgroundColor: COLORS.rowBg,
    borderRadius: 16,
    overflow: 'hidden', // keeps each row's bottom border from poking past the rounded corners
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  // Each individual tappable row inside a section card
  settingRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F6F5', // thin divider between rows
  },
  // Removes the divider on the last row in each section, so the
  // section card's bottom edge looks clean
  settingRowLast: {
    borderBottomWidth: 0,
  },
  rowText: {
    fontSize: 14,
    color: COLORS.rowText,
  },

  // ── Sign out link ──────────────────────────────────────────────
  signOutBtn: {
    alignItems: 'center',
    paddingVertical: 12,
    marginTop: 4,
  },
  signOutText: {
    fontSize: 15,
    fontWeight: '600',
    color: COLORS.signOutText,
  },

});